config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :nannies, only: [:new, :create, :index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index] do
    resources :reviews, only: :create
    member do
      patch '/accept', to: 'bookings#accept'
      patch '/reject', to: 'bookings#reject'
    end
  end # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :nanny
  has_one :review
  has_one_attached :photo

  def color
    if status == 'accepted'
      return 'green'
    elsif status == 'rejected'
      return 'red'
    else
      return 'grey'
    end
  end
end

app/models/nanny.rb
class Nanny < ApplicationRecord
  has_many :bookings
  has_many :reviews, through: :bookings
  belongs_to :user
  validates :user, uniqueness: true
  validates :price_per_hour, :description, :age, :city, presence: true
  has_one_attached :photo
  validates :city, presence: true
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
  include PgSearch::Model
  pg_search_scope :search_by_city,
  against: [ :city ],
  using: {
    tsearch: { prefix: true }
  }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  validates :content, length: { minimum: 10 }, presence: true
  RATINGS = [1, 2, 3, 4, 5]
  validates :rating, presence: true, numericality: true, inclusion: {in:  RATINGS}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :nanny
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    if current_user.nanny && current_user.nanny.bookings.any?
      @bookings = current_user.nanny.bookings
    end
      @request_bookings = current_user.bookings
      @review = Review.new
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
    redirect_to bookings_path
  end


  def new
    @booking = Booking.new
    @nanny = Nanny.find(params[:nanny_id])
  end

  def create
    @booking = Booking.new(bookings_params)
    @booking.user = current_user
    @nanny = Nanny.find(params[:nanny_id])
    @booking.nanny = @nanny
    if @booking.save
      redirect_to bookings_path, notice: 'booking created! Waiting for Nanny to accept offer'
    else
      render :new
    end
  end

 private

  def bookings_params
    params.require(:booking).permit(:address, :kids_number, :message, :start_date, :end_date, :photo)
  end
end

app/controllers/nannies_controller.rb
class NanniesController < ApplicationController

  def index
    @nannies = Nanny.geocoded #returns flats with coordinates
      if params[:query].present?
      @nannies = Nanny.search_by_city(params[:query])
      @markers = @nannies.map do |nanny|
      {
        lat: nanny.latitude,
        lng: nanny.longitude
      }
      end
      else
        @markers = @nannies.map do |nanny|
      {
        lat: nanny.latitude,
        lng: nanny.longitude
      }
    end
    end
  end

  def show
    @nanny = Nanny.find(params[:id])
    @review = Review.new
    @markers = [{

      lat: @nanny.latitude,
      lng: @nanny.longitude
    }]
  end


  def new
    @nanny = Nanny.new
  end

  def create
    @nanny = Nanny.new(nannies_params)
    @nanny.user = current_user
    if @nanny.save
      redirect_to nanny_path(@nanny), notice: 'nanny created! Welcome'
    else
      render :new
    end
  end

  private

  def nannies_params
    params.require(:nanny).permit(:city, :description, :age, :experience_level, :price_per_hour, :certification, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.booking = @booking
    if @review.save
      redirect_to bookings_path
    else
      @nanny = @booking.nanny
      render 'bookings/new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div id="height_adj_banner" class="sign-up-wrapper" style="background-image: url(https://res.cloudinary.com/dvallavgs/image/upload/v1584706887/test_rxhtzk.jpg)">
  <% if current_user.nanny %>


    <div class="container">
      <div class="row">
        <div class="col">
          <% if current_user.nanny.bookings.any? %>
            <h1 class="btn-dash text-center"> My dashboard </h1>
            <br>
            <div class="avatar-test">
            <% @bookings.each do |booking| %>
              <div class="notification">
                <% if booking.photo.attached? %>
                  <div style="background-image: url(<%= cl_image_path booking.photo.key %>)" class='avatar-large'> </div>
                <% else %>
                  <img src='https://kitt.lewagon.com/placeholder/users/random' class="avatar-large" />
                <% end %>
                <div class="notification-content">
                  <p><small> from <%= booking.start_date.strftime("%m-%e-%y %H:%M") %> until <%= booking.end_date.strftime("%m-%e-%y %H:%M") %> </small></p>
                  <p><%= booking.message %> <strong>"<%= booking.user.name %>"</strong> kids: <%= booking.kids_number %> </p>
                </div>

                <div class="notification-actions-btn">
                  <a><%= link_to("accept", accept_booking_path(booking), method: :patch, class: "accept-btn #{booking.status == 'accepted' ? 'confirmed' : ''}") %> </a>
                  <a><%= link_to("reject", reject_booking_path(booking), method: :patch, class: "reject-btn #{booking.status == 'rejected' ? 'confirmed' : ''}") %> <!-- <i class="far fa-times-circle"></i> --></a>
                </div>
            </div>
            <br>
            <% end %>
          </div>
        <% else %>
          <p> you have no bookings yet ... </p>
        <% end %>
        </div>
      </div>
    </div>

  <% else %>

    <div class="container">
      <div class="row">
        <div class="col">
          <h1 class="btn-dash text-center"> My dashboard </h1>
          <br>
          <div class="avatar-test">
            <% @request_bookings.each do |f| %>
            <%= link_to nanny_path(f.nanny) do  %>
            <div class="notification-review">
              <div class="notification">
                <% if f.nanny.photo.attached? %>
                  <div style="background-image: url(<%= cl_image_path f.nanny.photo.key %>)" class='avatar-large'> </div>
                <% else %>
                  <img src='https://kitt.lewagon.com/placeholder/users/random' class="avatar-large" />
                <% end %>
                <% end %>
                <div class="notification-content">
                    <p><small> from <%= f.start_date.strftime("%m-%e-%y %H:%M") %> until <%= f.end_date.strftime("%m-%e-%y %H:%M") %> </small></p>
                    <p><%= f.nanny.description %> <strong>"<%= f.nanny.user.name %>"</strong></p>
                </div>
                <div class="notification-actions <%= f.color %>">
                    <p> <%= f.status %> </p>
                </div>
              </div>
                  <% if f.review %>
                    <div class="review">
                      <%= f.review.content %>
                      <% f.review.rating.times do %>
                      <i class="fas fa-star m-1 "></i>
                    <% end %>
                    </div>
                  <% elsif f.status == "accepted" %>
                    <%= render 'reviews/form', booking: f, review: @review %>
                  <% end %>
                </div>
            <br>
          <% end %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="sign-up-wrapper" style="background-image: url(https://res.cloudinary.com/dvallavgs/image/upload/v1584457046/woman-holding-baby-while-sitting-on-fur-bean-bag-698878_rtfmhk.jpg)">
  <div class="container mx-0 h-100">
    <div class="row h-100">
      <div class="col-xs-12 col-md-6 offset-md-1 black_bgr mt-3">
       <h1 class="text-center">Book your nanny!</h1>
        <%= simple_form_for [@nanny, @booking] do |f| %>
        <div class="short_input">
        <%= f.input :address %>
        <%= f.input :kids_number, input_html: { min: "0" }, label: "number of kids" %>
        <%= f.input :message %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.input :photo, as: :file, label: "choose a picture of your kids!" %>
        </div>
        <div class="text-center">
        <%= f.submit "Submit", class: "btn btn-primary btn-submit w-100" %>
        </div>

        <% end %>

        <div class="text-center mt-3">
          <%= link_to "Go back", nannies_path, class: "btn btn-primary btn-submit w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <title>Rent a Nanny</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/nannies/index.html.erb
<div class="container">

  <%= form_tag nannies_path, method: :get do %>
  <div class="search-form-control form-group">
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search by city"
    %>
     <%= button_tag(type: "submit", class:"btn btn-search") do  %>
      <i class="fas fa-search"></i> Search
      <% end %>
  </div>
  <% end %>
  <div class="row">
    <% @nannies.each do |nanny| %>
    <div class="col-4 mt-4">
      <%= link_to nanny_path(nanny) do  %>
      <div class="card-nanny">
        <div class="hover-img">
          <% if nanny.photo.attached? %>
          <%= cl_image_tag nanny.photo.key, class: "card-img-top" %>
          <% else %>
          <%= image_tag "https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1145&q=80", class: "card-img-top"%>
          <% end %>
          <p class='price'><%= nanny.price_per_hour %>€</p>
          <h5 class="card-description text-center my-auto"><%= nanny.description %></h5>
        </div>
        <div class="card-body">
          <div class="card-see-more text-center">
            <p class="user-name"><%= nanny.user.name %></p>
          </div>
          <div class="d-flex justify-content-between">
            <p class="city-name ml-3"><%= nanny.city %></p>
            <!-- <p class="mr-3"><%#= nanny.booking.review.rating %><i class="fas fa-star m-1 "></i></p> -->
          </div>
            <%#= link_to "See More", nanny_path(nanny), class: "btn btn-primary btn-black btn-submit" %>

        </div>
      </div>
      <% end %>
    </div>
      <% end %>
    </div>
  </div>
  <div
  id="map"
  style="width: 100%;
  height: 300px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

app/views/nannies/new.html.erb
<div class="sign-up-wrapper" style="background-image: url(https://res.cloudinary.com/dvallavgs/image/upload/v1584457046/woman-holding-baby-while-sitting-on-fur-bean-bag-698878_rtfmhk.jpg)">
  <div class="container mx-0 h-100">
    <div class="row">
      <div class="col-xs-12 col-md-6 offset-md-1 black_bgr mt-3">
    <h1 class="text-center">Become a nanny!</h1>
        <%= simple_form_for @nanny do |f| %>
        <div class="short_input">
        <%= f.input :city %>
        <%= f.input :age, input_html: { min: "0" } %>
        <%= f.input :description %>
        <%= f.input :experience_level, input_html: { min: "0", max: "5" } %>
        <%= f.input :price_per_hour, input_html: { min: "0" } %>
        <%= f.input :certification %>
        <%= f.input :photo, as: :file %>

        </div>
        <div class="text-center">
        <%= f.submit "Submit", class: "btn btn-primary btn-submit w-100" %>
        </div>

        <% end %>

        <div class="text-center mt-3">
          <%= link_to "Go back", nannies_path, class: "btn btn-warning btn-sm btn-submit w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/nannies/show.html.erb
  <div class="d-flex justify-content-between bg-white">
    <div class="w-50 mx-3 mt-1 card-show">
      <div>
        <% if @nanny.photo.attached? %>
        <div class= "text-center">
        <%= cl_image_tag @nanny.photo.key, class: "card-image w-50" %>
        </div>
        <% end %>
      </div>
      <div class="mt-3">
        <h2 class="text-center"><%= @nanny.user.name %></h2>
        <div class="d-flex justify-content-between my-3">
          <div>
            <p><strong>Description: </strong><%= @nanny.description %></p>
            <p><strong>Location: </strong><%= @nanny.city %></p>
            <% if @nanny.certification %>
              <p><strong>Certified in: </strong><%= @nanny.certification %></p>
            <% end %>
          </div>
          <div>
            <p><strong>Rate: </strong><%=@nanny.price_per_hour%>€ per hour</p>
            <p><strong>Age: </strong><%= @nanny.age %></p>
          </div>
        </div>
      <div><%= link_to "Book now!", new_nanny_booking_path(@nanny), class: "btn btn-success w-100" %></div>
      <p><%= link_to 'Back to all nannies', nannies_path, class: "btn btn-primary btn-black btn-submit w-100" %></p>
    <br>
    <div class="reviews">
      <h2>Reviews</h2>
    <% @nanny.reviews.each do |review|%>
    <div class="review">
    <p><strong><%= review.booking.user.name %> says:</strong></p>
    <p><%= review.content %></p>
    <% review.rating.times do %>
    <i class="fas fa-star m-1 "></i>
    <% end %>
    </div>
    <% end %>
    </div>
  </div>
    </div>
      <div
        id="map"
        style="width: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>

app/views/pages/home.html.erb
<main class="wrapper">
  <section class="hero">
    <h1>Need a hand?</h1>
    <article>
        <p>Browse nannies in your area that can provide the support you need in your busy life.</p>
    </article>
    <%= link_to nannies_path do %>
    <button type="button" class="btn btn-success">Find a Nanny</button>
    <% end %>
    <% if current_user&.nanny %>
    <%= link_to bookings_path do %>
    <button type="button" class="btn btn-primary btn-submit">My Dashboard</button>
    <% end %>
    <% else %>
    <%= link_to new_nanny_path do %>
    <button type="button" class="btn btn-primary btn-submit">Become a Nanny</button>
    <% end %>
    <% end %>
  </section>
</main>

app/views/reviews/_form.html.erb
<%= simple_form_for([ booking, review ])  do |form| %>
<div class='d-flex justify-content-between'>
  <%= form.input :content, class: 'mr-4', input_html: { class: 'long-input' } %>
  <%= form.input :rating, collection: Review::RATINGS, input_html: { class: 's-input' }  %>
  </div>
<div class="d-flex justify-content-center">
  <%= form.button :submit, 'send review!', class: 'grey' %>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "lelogo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="background-color: white;">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if current_user&.nanny %>
        <%= link_to root_path do %>
        <%= link_to "My Dashboard", bookings_path, class: "nav-link" %>
        <% end %>
        <% else %>
        <%= link_to new_nanny_path do %>
        <%= link_to "Become a Nanny", new_nanny_path, class: "nav-link" %>
        <% end %>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My Profile", bookings_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>